### ISSUE TITLE
Unable to bind to dynamic ports (Heroku)

### ISSUE THREAD

**Issue by patrickmichalina** [aerojs/aero#102]
One should be able to bind to a port set in process.env.PORT variable.

https://github.com/aerojs/aero/blob/94b6ec4838e695f3c90b122f3ed01e6d19bf7db7/lib/Server/run.js#L64

**Comment by akyoto** [comment]
I've never worked with Heroku, but I believe the pull request you sent earlier fixed the issue?

https://github.com/aerojs/aero/releases/tag/v2.1.0

**Comment by patrickmichalina** [comment]
It did, thank you!
