### ISSUE TITLE
Middleware Proxy

### ISSUE THREAD

**Issue by TakaharaShujin** [aerojs/aero#75]
Can i use middleware in local server for api requests ?

**Comment by blitzprog** [comment]
Could you elaborate what exactly you are trying to achieve?

[Registering standard middleware](https://github.com/aerojs/aero/blob/master/docs/API.md#middleware) works but it is global and affects all routes. Specifying different middleware for different routes would be nice to have but it is not implemented yet.

If it's something you absolutely need to do you can use a workaround for now and add a condition based on `request.url` inside the middleware function, basically doing your own little routing check.

Is that what you meant or did I misunderstand you?

**Comment by TakaharaShujin** [comment]
API in the project I'm working, it's the http://gaaraj.com/api address. I can not send requests to the API, because it prevented cross-origin requests on the server side and does not work with my requests that I sent localholst.
I could do it with a grunt, but I have not yet adapted to node fws :)
Grunt connect code as follows;
```javascript
connect: {
    options: {
        port: 3000,
        hostname: 'localhost',
        livereload: 35729,
        bases: 'build'
    },
    livereload: {
        options: {
            open: true,
            middleware: function(connect) {
                var url = require('url');
                var proxy = require('proxy-middleware');
                return [
                    connect().use('/api', proxy(url.parse('https://gaaraj.com/api'))),
                    require('connect-modrewrite')(['^[^\\.]*$ /index.html [L]']),
                    connect.static('build')
                ];
            }
        }
    }
}
```

**Comment by blitzprog** [comment]
So Aero is preventing the access server-side from https://gaaraj.com/api while accessing it from a connect client?
That is very strange. Which HTTP status code do you get for the failing requests?

**Comment by TakaharaShujin** [comment]
In fact, as follows:
I going to use the aero like a static server. I don't want to use php. I will send the request to api with jquery. But browser send cross-origin error when ajax url is http://gaaraj.com/api.

I found the answer to my question. This codes is works :)
```javascript
'use strict';
let aero = require('aero')
let request = require('request')
let app = aero()
let url = require('url')
let proxy = require('http-proxy-middleware')

app.use(proxy('/api', {
    target: 'https://www.gaaraj.com',
    changeOrigin: true,
    ws: true,
}))

app.run()
```

**Comment by blitzprog** [comment]
I'm happy that you found a solution for your problem :)

Note that jQuery is not officially supported as it conflicts with [aero-ajax](https://github.com/aerojs/aero-ajax) plugin which serves as a replacement for the most common jQuery functions and is much smaller. However it only supports very basic stuff like e.g. `$.get` and `$.post` so if you need advanced jQuery functionality then indeed you can't get around jQuery (even though it's a huge library, in terms of file size).

**Comment by TakaharaShujin** [comment]
Thanks :) jQuery is a example, It may be other front-end frameworks. Aero is beautiful and simple framework. After that, it looks like I'm going to use the aero often :)
