### ISSUE TITLE
 Automatically changing the page title

### ISSUE THREAD

**Issue by TakaharaShujin** [aerojs/aero#79]
It does not change the title of the page when the page is changed. Is there a way to do this automatically? For example, a different title in every product. So page title vary by product. But, page title is static on config.json.

**Comment by blitzprog** [comment]
Hi. You yourself decide which title is going to be used. See [Layout](https://github.com/aerojs/aero/blob/master/docs/Layouts.md).

The default, if no layout file is used, is this:

```jade
title= app.config.title
```

But you can change it to something different:

```jade
title= app.config.title + ' - ' + page.json.title
```

The only problem is it doesn't automatically change when the aero-ajax plugin is used. Header changes on AJAX requests are difficult to implement and not available yet.

**Comment by blitzprog** [comment]
Let me know about the problems you're facing (concerning this issue).
In case there are no problems remaining, let's close this issue.

**Comment by TakaharaShujin** [comment]
Sorry, my fault. I'm a little busy, completely slipped my mind. I'm closing now, thanks for answer. I think aero will come to a better place :)
