### ISSUE TITLE
Proper way to use socket.io with aero?

### ISSUE THREAD

**Issue by JohnPittman** [aerojs/aero#82]
How do I get the instance of the http server to init socket.io?
I guessed this:

const server = app.run();

const io = require('socket.io')(server);

io.on('connection', (socket) => {
  console.log('a user connected');
 
  socket.on('disconnect', () => {
    console.log('user disconnected');
  });
});

**Comment by blitzprog** [comment]
I don't know socket.io but this is how you can access it: `app.server.http`

`app.server` gives you the Aero Server instance and `app.server.http` gives you the `http` or `node-spdy` server object.

`app.run()` returns `app.ready` which is a promise that gets fulfilled when the server loaded all pages and started the server.

So I recommend doing it like this:

```js
app.run().then(() => {
	console.log(app.server.http)
})
```

**Comment by blitzprog** [comment]
Oh, I just realized that I didn't upload these changes yet.
The currently released module requires `app.server.httpServer`, **not** `app.server.http`.
Sorry for the misleading information.

**Comment by blitzprog** [comment]
As of [1.4.2](https://github.com/aerojs/aero/commit/f3016a56b9d3b5f492f16c12d2ea57d134bc91e8) which was released today the correct way to access the server object is `app.server.http` and has also been included in the documentation now.

**Comment by JohnPittman** [comment]
You are awesome. Thanks!
