### ISSUE TITLE
How to use app variable in pages ?

### ISSUE THREAD

**Issue by TakaharaShujin** [aerojs/aero#84]
My index.js file is;
``` javascript
'use strict';

let aero = require('aero')
let app = aero()
let PouchDB = require('pouchdb');
let database = new PouchDB('http://localhost:5984/passsbanker');

app.database = database;
app.run()
```
I want, get db records in pages. Am i access to app variable in pages globally ?

**Comment by blitzprog** [comment]
See [template globals](https://github.com/aerojs/aero/blob/master/docs/Templates.md#globals).

"Every Jade template has access to the app variable. Page templates can additionally access their own page data via the page variable."

Yes, you can access `app` as a special global in templates.

From a *code design standpoint* it makes more sense to query the database in the controller and pass the result to the template. The template should not care about where the data comes from. This would be a cleaner, recommended solution.

**Comment by TakaharaShujin** [comment]
I read it documents but im not use app variable in templates. Im using in controller file. What should i do ?

**Comment by blitzprog** [comment]
Inside a controller method:
```js
this.app
this.page
```

**Comment by TakaharaShujin** [comment]
I tested your code just now and that works. Thanks!
