### ISSUE TITLE
Unknown plugin error in aero-ajax

### ISSUE THREAD

**Issue by TakaharaShujin** [aerojs/aero#85]
I install aerojs then add aero-ajax plugin to my project. Throw this error during the run. Any idea this problem ?

```
ReferenceError: Unknown plugin "babel-plugin-transform-es2015-template-literals" specified in "base" at 0, attempted to resolve relative to "projects-path\\node_modules\\aero-ajax\\lib\\functions"
```

**Comment by blitzprog** [comment]
Just letting you know that I've read your issue but I'm a bit busy now and fixing it will have to wait.
Unless someone else in the OS community has the time to fix this problem.

I guess some external packages have been updated and the code needs to be adjusted.

**Comment by TakaharaShujin** [comment]
No problem, actually I'm busy like you but i love aero and I want to have contributed to its development

**Comment by blitzprog** [comment]
Is this problem still occurring?

**Comment by TakaharaShujin** [comment]
i installed it few moments ago and I encountered no problems.
