### ISSUE TITLE
Server stop error

### ISSUE THREAD

**Issue by TakaharaShujin** [aerojs/aero#87]
When I make changes to the configuration file I get this error:
[http://pasteboard.co/f08BvwUjj.jpg](http://pasteboard.co/f08BvwUjj.jpg)

**Comment by blitzprog** [comment]
I also see some problems restarting after `config.json` changes.

Sadly modifications of the core configuration are very difficult to handle without a manual restart.
I haven't figured out yet how to do a completely clean restart of all HTTP and WebSockets but this is an ongoing effort.

In the meantime, I suggest you restart the app manually after `config.json` changes.
Sorry for the inconveniences.
