### ISSUE TITLE
How to use route parameters ?

### ISSUE THREAD

**Issue by TakaharaShujin** [aerojs/aero#94]
How to use advanced route parameters in aero like expressjs ?
Expressjs docs: https://expressjs.com/en/guide/routing.html#route-parameters

```
Route path: /flights/:from-:to
Request URL: http://localhost:3000/flights/LAX-SFO
req.params: { "from": "LAX", "to": "SFO" }
```

https://github.com/aerojs/aero/blob/master/lib/App/route.js#L3
Aero had used regexp url in route.js:3 but how to define url in examplepage.json for regexp url ?

**Comment by blitzprog** [comment]
#73 - work in progress :)
It won't support your example, though. This can be done in the current version via regex routing.

**Comment by TakaharaShujin** [comment]
Thank you, i getting follow issue #73 👍
