### ISSUE TITLE
GPL -> LGPL/ZLIB/BSD/MIT?

### ISSUE THREAD

**Issue by ghost** [aerojs/aero#98]
Nice project, I did some quick benchmarking:

Sails.js: less than 2k requests/second
Expressjs: 12k r/s
Aerojs: 28k r/s
Node.js vanilla: 38k r/s

Looks promising, but I'm pretty sure GPL is not the right license for a library. At least swap to LGPL so that users won't have to relicense all of their code as GPL (it spreads like a cancer if not contained). LGPL at least has a barrier between library and user code and allows the two parts to work with their own licenses. GPL is okay for projects that are naturally contained, like a stand alone executable, but not for libraries.

/ opinion

**Comment by akyoto** [comment]
Under consideration.

Sorry that I can't be more precise.

**Comment by ghost** [comment]
Hey that's totally up to you. It runs fast and has a nice interface so I think the lib could become very popular with a more permissive license.

**Comment by amitguptagwl** [comment]
@alexhultman can you plz share the sample code you run to test the performance? And platform detail as well along with which version of nodejs were you using?

I'll try to test it against other frameworks too.

@blitzprog I would like to echo @alexhultman's word about licensing. However up to you :)

**Comment by ghost** [comment]
You're probably better off looking at https://github.com/lukeed/polka instead, it does perform similarly if not better and has an MIT license.

**Comment by akyoto** [comment]
Polka looks really good. I'd also recommend it since this library is not in active development anymore.

If someone however wants to take over the project and maintain it, feel free to message me.

**Comment by akyoto** [comment]
Though it's a bit late, I [switched the license to MIT](https://github.com/aerojs/aero/commit/2e5ba9847f57c75a19925f9300a1313ac9350869) now. Feel free to use the code however you like.
